repos:
-   repo: local
    hooks:
    -   id: docker-flake8
        name: Linter (Flake8 in Docker)
        entry: docker compose run --rm -T backend flake8 --config=app/.flake8 app/
        language: system
        pass_filenames: false

    -   id: docker-pytest
        name: Tests (Pytest in Docker)
        entry: docker compose run --rm -T backend pytest
        language: system
        pass_filenames: false
        stages: [commit]